run:
linters-settings:
linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - prealloc
    - scopelint
    - staticcheck
    - stylecheck
    - structcheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - vet

