version: 2.1

executors:
  # Whenever the Go version is updated here, .travis.yml and .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.12
      environment:
          GO111MODULE: "on"

  fuzzit:
    docker:
      - image: fuzzitdev/golang:1.12.7-buster
        environment:
          GO111MODULE: "off"

jobs:
  test:
    executor: golang
    working_directory: /go/src/github.com/marten-seemann/qpack
    steps:
      - checkout
      - run:
          name: "Setup build environment"
          command: |
            git submodule update --init --recursive
            go get github.com/onsi/ginkgo/ginkgo
            go get github.com/onsi/gomega
      - run:
          name: "Build infos"
          command: go version
      - run:
          name: "Run unit tests"
          command: ginkgo -race -cover -v -randomizeAllSpecs
      - run:
          name: "Run integration tests"
          command: ginkgo -r -race -v -randomizeAllSpecs -trace integrationtests
      - run:
          name: "Upload coverage report to Codecov"
          when: on_success
          command: |
            cat `find . -name "*.coverprofile"` > coverage.txt
            bash <(curl -s https://codecov.io/bash) -f coverage.txt
  fuzzit:
    executor: fuzzit
    working_directory: /go/src/github.com/marten-seemann/qpack
    steps:
      - checkout
      - setup_remote_docker
      - run: go get ./...
      - run: .circleci/fuzzit.sh

workflows:
  version: 2
  qpack:
    jobs:
    - test
    - fuzzit
    